# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 18e7005
_src_path: gh:scipp/copier_template
description: Handbooks for Experiments by ESS-DMSC
max_python: '3.12'
min_python: '3.10'
namespace_package: ''
nightly_deps: ''
orgname: ess-dmsc-dram
prettyname: Experiments-Handbook
projectname: experiments-handbook
related_projects: ''
year: 2025
