name: Release

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}  # required for conda env

jobs:
  docs:
    with:
      publish: true
    uses: ./.github/workflows/docs.yml
    secrets: inherit

  assets:
    name: Upload docs
    needs: docs
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: write  # This is needed so that the action can upload the asset
    steps:
    - uses: actions/download-artifact@v4
    - name: Zip documentation
      run: |
        mv docs_html documentation-${{ github.ref_name }}
        zip -r documentation-${{ github.ref_name }}.zip documentation-${{ github.ref_name }}
    - name: Upload release assets
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./documentation-${{ github.ref_name }}.zip
        overwrite: false
